name = "SOG Experience"
author = "Sendout"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "257ddb18bb57eb81cc191b0e52daef0ad06e4d5f4fdc53665250d9e7add4b729"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
