name = "SOG Experience"
author = "Sendout"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4639acf4152fd839471fa7cd5a13bf20f6f268009f9d441f5e470b4123505a58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
