name = "SOG Experience"
author = "Sendout"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77abc855e83d51b8edeb85ae7855ac9d8119c83cd494289f716cfec5222b5566"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
